---
- name: http install
  hosts: all
  become: yes

  tasks:
    - name: httpd install
      yum:
        name: httpd
        state: present

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false

    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: index.html creation
      copy:
        src: index.html
        dest: /var/www/html/index.html
